image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
<<<<<<< HEAD
    EXEC: hi
    HW_DIR: hw0
    CPU_LIMIT: 10
=======
    EXEC: dtmf
    HW_DIR: hw1
    CPU_LIMIT: 60
>>>>>>> HW1_CODE/master
    FILE_LIMIT: 1000000
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
        - ulimit -t ${CPU_LIMIT} -f ${FILE_LIMIT}
<<<<<<< HEAD
        - ${HW_DIR}/bin/${EXEC}
=======
        - cd ${HW_DIR} && bin/${EXEC} -h
>>>>>>> HW1_CODE/master
test:
    stage: test
    script:
        - ulimit -t ${CPU_LIMIT} -f ${FILE_LIMIT}
<<<<<<< HEAD
        - ${HW_DIR}/bin/${EXEC}_test -S --verbose=0 --timeout 5
=======
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 --timeout 5
>>>>>>> HW1_CODE/master
